name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Install npm dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

      - name: Unit tests
        run: bundle exec rspec

#      - name: Check data structure
#        run: make validate

      - name: Check Jekyll configuration
        run: bundle exec jekyll doctor

      - name: Jekyll build
        run: bundle exec jekyll build --trace

#      - name: Check HTML common mistakes
#        run: make html-proofer

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: _site
          extra: --ignore 'Element "img" is missing required attribute "src"'
          skip_git_check: true

      - name: Wait for server to start
        run: |
          (bundle exec jekyll serve --no-watch --skip-initial-build)&
          while ! curl --silent http://localhost:4000
          do sleep 1
          done
